# Import Library

In [169]:
import pandas as pd
import numpy as np
import csv
import re
from nltk.tokenize import RegexpTokenizer

In [170]:
# Python script for confusion matrix creation. 
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

from sklearn.metrics import f1_score

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Methods

In [218]:
# load_file = pd.read_csv('Dataset/Pure MI/10persenMI.csv', index_col= None)
load_file_wsw = pd.read_csv('Dataset/Pure MI/MI (no stem and no sw)/10persenMInostem&nosw.csv', index_col = None)
# load_file = load_file.drop('Unnamed: 0', axis=1)
load_file_wsw = load_file_wsw.drop('Unnamed: 0', axis=1)

In [219]:
stopwords = load_txt('stopwords.txt')

# Main Pure MI Data

In [220]:
load_file_wsw

goblok  tolol  bego  bodoh  alay  dungu   si  kamu  dasar  idiot  ...  \
0        0.0    0.0   0.0    0.0   0.0    0.0  0.0   2.0    0.0    0.0  ...   
1        1.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
2        0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
3        0.0    0.0   0.0    0.0   0.0    0.0  0.0   1.0    0.0    0.0  ...   
4        0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
5        0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
6        0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
7        0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
8        0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
9        0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
10       0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
11       0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
12       0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
13       0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
14       0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
15       0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
16       0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
17       0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
18       0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
19       0.0    0.0   0.0    0.0   0.0    0.0  0.0   1.0    0.0    0.0  ...   
20       0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
21       0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
22       0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
23       0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
24       0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
25       0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
26       0.0    0.0   0.0    0.0   0.0    0.0  0.0   3.0    0.0    0.0  ...   
27       0.0    0.0   0.0    1.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
28       0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
29       0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
...      ...    ...   ...    ...   ...    ...  ...   ...    ...    ...  ...   
3150     0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
3151     0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
3152     0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
3153     0.0    0.0   0.0    0.0   0.0    0.0  0.0   1.0    0.0    0.0  ...   
3154     0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
3155     0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
3156     0.0    0.0   0.0    0.0   0.0    0.0  0.0   1.0    0.0    0.0  ...   
3157     0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
3158     0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
3159     0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
3160     0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
3161     0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
3162     0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
3163     0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
3164     0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
3165     0.0    0.0   2.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
3166     0.0    0.0   0.0    0.0   0.0    0.0  0.0   1.0    0.0    0.0  ...   
3167     0.0    0.0   0.0    0.0   0.0    0.0  0.0   0.0    0.0    0.0  ...   
3168     0.0    0.0   0.0    0.0   0.0    0.0  0.0   1.0

In [221]:
value_ekstraksi = load_file_wsw.drop('Label', axis=1)
# value_ekstraksi

In [222]:
label_ekstraksi = load_file_wsw['Label']
# label_ekstraksi

In [223]:
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(value_ekstraksi, label_ekstraksi, test_size=0.3) # 70% training and 30% test

In [224]:
#Import knearest neighbors Classifier model
from sklearn.neighbors import KNeighborsClassifier

#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=4)

#Train the model using the training sets
knn.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = knn.predict(X_test)

In [225]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8679245283018868


In [226]:
y_true = y_test
print(f1_score(y_true, y_pred, average='macro'))
print(f1_score(y_true, y_pred, average='micro'))
print(f1_score(y_true, y_pred, average='weighted')) 
print(f1_score(y_true, y_pred, average=None))

0.30976430976430974
0.8679245283018869
0.8065561273108444
[0.92929293 0.         0.        ]


/Users/dhamirdesrul/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [227]:
results = confusion_matrix(y_true, y_pred) 
print('Confusion Matrix :')
print(results) 
print('Accuracy Score :',accuracy_score(y_true, y_pred))
print('Report : ')
print(classification_report(y_true, y_pred))

Confusion Matrix :
[[828   0   0]
 [ 33   0   0]
 [ 93   0   0]]
Accuracy Score : 0.8679245283018868
Report : 
              precision    recall  f1-score   support

           1       0.87      1.00      0.93       828
           2       0.00      0.00      0.00        33
           3       0.00      0.00      0.00        93

   micro avg       0.87      0.87      0.87       954
   macro avg       0.29      0.33      0.31       954
weighted avg       0.75      0.87      0.81       954



/Users/dhamirdesrul/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
