In [330]:
import pandas as pd
import numpy as np
import collections
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn import metrics
import csv
from sklearn.model_selection import RepeatedKFold

In [331]:
# Python script for confusion matrix creation. 
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

from sklearn.metrics import f1_score

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

In [466]:
load_file = pd.read_csv('bagofwords_no stem&nosw.csv', index_col= None)
load_file = load_file.drop('Unnamed: 0', axis=1)

In [467]:
load_file

_    a   aa   ab  abadi  abai  abal  abang  abdi  abg  ...  zero   zo  \
0     0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
1     0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
2     0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
3     0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
4     0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
5     0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
6     0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
7     0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
8     0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
9     0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
10    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
11    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
12    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
13    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
14    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
15    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
16    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
17    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
18    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
19    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
20    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
21    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
22    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
23    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
24    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
25    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
26    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
27    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
28    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
29    0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
...   ...  ...  ...  ...    ...   ...   ...    ...   ...  ...  ...   ...  ...   
3150  0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
3151  0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
3152  0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
3153  0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
3154  0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
3155  0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
3156  0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
3157  0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
3158  0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
3159  0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
3160  0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
3161  0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
3162  0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
3163  0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
3164  0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
3165  0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
3166  0.0  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0  ...   0.0  0.0   
3167  0.0  0.0  0.0  0.0    0.0   0.0  

In [468]:
len(load_file)

3180

In [469]:
value_ekstraksi = load_file.drop('Label', axis=1)
# value_ekstraksi

In [470]:
label_ekstraksi = load_file['Label']
# label_ekstraksi

In [471]:
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(value_ekstraksi, label_ekstraksi, test_size=0.33) # 70% training and 30% test

In [473]:
# y_train

In [474]:
gnb = GaussianNB()

gnb.fit(X_train, y_train)

ab = gnb.predict(X_test)

y_pred = ab

In [475]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7571428571428571


In [476]:
y_true = y_test
print(f1_score(y_true, y_pred, average='macro'))
print(f1_score(y_true, y_pred, average='micro'))
print(f1_score(y_true, y_pred, average='weighted')) 
print(f1_score(y_true, y_pred, average=None))

0.33982754511748614
0.7571428571428571
0.7738709744774471
[0.86811352 0.02409639 0.12727273]


In [477]:
results = confusion_matrix(y_true, y_pred) 
print('Confusion Matrix :')
print(results) 
print('Accuracy Score :',accuracy_score(y_true, y_pred))
print('Report : ')
print(classification_report(y_true, y_pred))

Confusion Matrix :
[[780  31 111]
 [ 32   1   7]
 [ 63  11  14]]
Accuracy Score : 0.7571428571428571
Report : 
              precision    recall  f1-score   support

           1       0.89      0.85      0.87       922
           2       0.02      0.03      0.02        40
           3       0.11      0.16      0.13        88

   micro avg       0.76      0.76      0.76      1050
   macro avg       0.34      0.34      0.34      1050
weighted avg       0.79      0.76      0.77      1050

