In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
import pandas as pd
import numpy as np
import collections
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn import metrics
import csv

In [6]:
# Python script for confusion matrix creation. 
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

from sklearn.metrics import f1_score

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

In [388]:
load_file = pd.read_csv('bagofwords.csv', index_col= None)
load_file = load_file.drop('Unnamed: 0', axis=1)

In [389]:
load_file

a   aa   ab  abadi  abai  abal  abang  abdi  abg  abis  ...  zero  \
0     0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
1     0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
2     0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3     0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
4     0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
5     0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
6     0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
7     0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
8     0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
9     0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
10    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
11    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
12    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
13    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
14    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
15    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
16    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
17    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
18    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
19    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
20    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
21    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
22    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
23    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
24    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
25    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
26    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
27    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
28    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
29    0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
...   ...  ...  ...    ...   ...   ...    ...   ...  ...   ...  ...   ...   
3150  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3151  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3152  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3153  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3154  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3155  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3156  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3157  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3158  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3159  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3160  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3161  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3162  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3163  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3164  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3165  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3166  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3167  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3168  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   0.0  ...   0.0   
3169  0.0  0.0  0.0    0.0   0.0   0.0    0.0   0.0  0.0   2.0  ...   0.0   
3170

In [390]:
load_file.shape

(3180, 5880)

In [356]:
value_ekstraksi = load_file.drop('Label', axis=1)

In [357]:
label_ekstraksi = load_file['Label']

In [358]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(value_ekstraksi, label_ekstraksi, test_size = 0.30)

In [383]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly',degree=2)
svclassifier.fit(X_train, y_train)

/Users/dhamirdesrul/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=2, gamma='auto_deprecated',
  kernel='poly', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [384]:
y_pred = svclassifier.predict(X_test)

In [385]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8658280922431866


In [386]:
y_true = y_test
print(f1_score(y_true, y_pred, average='macro'))
print(f1_score(y_true, y_pred, average='micro'))
print(f1_score(y_true, y_pred, average='weighted')) 
print(f1_score(y_true, y_pred, average=None))

0.3093632958801498
0.8658280922431866
0.8035662968459238
[0.92808989 0.         0.        ]


/Users/dhamirdesrul/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [387]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[826   0   0]
 [ 34   0   0]
 [ 94   0   0]]
              precision    recall  f1-score   support

           1       0.87      1.00      0.93       826
           2       0.00      0.00      0.00        34
           3       0.00      0.00      0.00        94

   micro avg       0.87      0.87      0.87       954
   macro avg       0.29      0.33      0.31       954
weighted avg       0.75      0.87      0.80       954



/Users/dhamirdesrul/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
